"""
Builds every picture in the game: SVG files in art/svg (for previews and the design guide) and
the Compose ImageVector code the app draws with. Run from reef/art: python3 build_art.py
"""
import os

from artlib import to_svg, to_kotlin
import catalog

HERE = os.path.dirname(os.path.abspath(__file__))
SVG_DIR = os.path.join(HERE, "svg")
KT_FILE = os.path.join(HERE, "..", "app", "src", "main", "kotlin", "com", "reef", "app", "ui", "art", "ArtLibrary.kt")

OBJECTS = {"creature": "Portraits", "suit": "Suits", "piece": "Tokens", "icon": "Icons", "deco": "Scenery"}


def camel(name):
    parts = name.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def main():
    arts = catalog.all_art()
    os.makedirs(SVG_DIR, exist_ok=True)
    for old in os.listdir(SVG_DIR):
        if old.endswith(".svg"):
            os.remove(os.path.join(SVG_DIR, old))
    for art in arts:
        with open(os.path.join(SVG_DIR, art.name + ".svg"), "w") as fh:
            fh.write(to_svg(art) + "\n")

    out = [
        "// Generated by art/build_art.py from the art sources in art/. Do not edit by hand.",
        "package com.reef.app.ui.art",
        "",
        "import androidx.compose.ui.graphics.StrokeCap",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "",
    ]
    for category, obj in OBJECTS.items():
        group = [a for a in arts if a.category == category]
        out.append(f"object {obj} {{")
        names = []
        for art in group:
            prefix = {"piece": "piece_", "icon": "icon_", "suit": "suit_", "deco": "deco_"}.get(category, "")
            name = camel(art.name[len(prefix):] if prefix and art.name.startswith(prefix) else art.name)
            names.append(name)
            out.append(to_kotlin(art, name))
            out.append("")
        out.append(f"    val all: List<ImageVector> get() = listOf({', '.join(names)})")
        out.append("}")
        out.append("")
    os.makedirs(os.path.dirname(KT_FILE), exist_ok=True)
    with open(KT_FILE, "w") as fh:
        fh.write("\n".join(out))
    size = os.path.getsize(KT_FILE)
    print(f"{len(arts)} pictures, {size // 1024} KB of Kotlin")


if __name__ == "__main__":
    main()
